export enum LIQUID_COMMERCE_ENV {
  LOC = 'loc',
  STAGE = 'stage',
  PROD = 'prod',
  DEV = 'dev',
}

export enum ENUM_MODALITIES {
  ON_DEMAND = 'onDemand',
  SHIPPING = 'shipping',
}

export enum DAYS_OF_WEEK {
  MONDAY = 'monday',
  TUESDAY = 'tuesday',
  WEDNESDAY = 'wednesday',
  THURSDAY = 'thursday',
  FRIDAY = 'friday',
  SATURDAY = 'saturday',
  SUNDAY = 'sunday',
}

export enum STATES_CODE {
  AL = 'AL',
  AK = 'AK',
  AR = 'AR',
  CA = 'CA',
  CO = 'CO',
  CT = 'CT',
  DE = 'DE',
  DC = 'DC',
  FL = 'FL',
  GA = 'GA',
  HI = 'HI',
  ID = 'ID',
  IL = 'IL',
  IN = 'IN',
  IA = 'IA',
  KS = 'KS',
  KY = 'KY',
  LA = 'LA',
  ME = 'ME',
  MD = 'MD',
  MA = 'MA',
  MI = 'MI',
  MN = 'MN',
  MS = 'MS',
  MO = 'MO',
  MT = 'MT',
  NE = 'NE',
  NV = 'NV',
  NH = 'NH',
  NJ = 'NJ',
  NM = 'NM',
  NY = 'NY',
  NC = 'NC',
  ND = 'ND',
  OH = 'OH',
  OK = 'OK',
  OR = 'OR',
  PA = 'PA',
  RI = 'RI',
  SC = 'SC',
  SD = 'SD',
  TN = 'TN',
  TX = 'TX',
  UT = 'UT',
  VT = 'VT',
  VA = 'VA',
  WA = 'WA',
  WV = 'WV',
  WI = 'WI',
  WY = 'WY',
}

export enum STATES_NAME {
  ALABAMA = 'AL',
  ALASKA = 'AK',
  ARKANSAS = 'AR',
  CALIFORNIA = 'CA',
  COLORADO = 'CO',
  CONNECTICUT = 'CT',
  DELAWARE = 'DE',
  DISTRICT_OF_COLUMBIA = 'DC',
  FLORIDA = 'FL',
  GEORGIA = 'GA',
  HAWAII = 'HI',
  IDAHO = 'ID',
  ILLINOIS = 'IL',
  INDIANA = 'IN',
  IOWA = 'IA',
  KANSAS = 'KS',
  KENTUCKY = 'KY',
  LOUISIANA = 'LA',
  MAINE = 'ME',
  MARYLAND = 'MD',
  MASSACHUSETTS = 'MA',
  MICHIGAN = 'MI',
  MINNESOTA = 'MN',
  MISSISSIPPI = 'MS',
  MISSOURI = 'MO',
  MONTANA = 'MT',
  NEBRASKA = 'NE',
  NEVADA = 'NV',
  NEW_HAMPSHIRE = 'NH',
  NEW_JERSEY = 'NJ',
  NEW_MEXICO = 'NM',
  NEW_YORK = 'NY',
  NORTH_CAROLINA = 'NC',
  NORTH_DAKOTA = 'ND',
  OHIO = 'OH',
  OKLAHOMA = 'OK',
  OREGON = 'OR',
  PENNSYLVANIA = 'PA',
  RHODE_ISLAND = 'RI',
  SOUTH_CAROLINA = 'SC',
  SOUTH_DAKOTA = 'SD',
  TENNESSEE = 'TN',
  TEXAS = 'TX',
  UTAH = 'UT',
  VERMONT = 'VT',
  VIRGINIA = 'VA',
  WASHINGTON = 'WA',
  WEST_VIRGINIA = 'WV',
  WISCONSIN = 'WI',
  WYOMING = 'WY',
}

export enum ENUM_ENGRAVING {
  YES = 'YES',
  NO = 'NO',
}

export enum ENUM_FILTER_KEYS {
  BRANDS = 'brands',
  FLAVOR = 'flavor',
  FULFILLMENT = 'fulfillment',
  TAGS = 'tags',
  REGION = 'region',
  VARIETY = 'variety',
  ENGRAVING = 'engraving',
  PRICE = 'price',
  AVAILABILITY = 'availability',
  CATEGORIES = 'categories',
  SIZES = 'sizes',
  COLORS = 'colors',
  APPELLATION = 'appellation',
  COUNTRY = 'country',
  VINTAGE = 'vintage',
  MATERIALS = 'materials',
  COLLECTION_TAGS = 'collectionTags',
}

export enum ENUM_NAVIGATION_ORDER_DIRECTION_TYPE {
  ASC = 'asc',
  DESC = 'desc',
}

export enum ENUM_ORDER_BY {
  PRICE = 'price',
}

export enum ENUM_AVAILABILITY_VALUE {
  UNSPECIFIED = 'AVAILABILITY_UNSPECIFIED',
  IN_STOCK = 'IN_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  PREORDER = 'PREORDER',
  BACKORDER = 'BACKORDER',
}

export enum CART_PARAM_ERROR_ENUM {
  INVALID_ITEMS_TYPE = 'Items must be a non-empty array',
  INVALID_ITEMS_MAX = 'You can only send up to 25 items at a time!',
  INVALID_PART_NUMBER = 'The partnerNumber provided is invalid',
  INVALID_FULFILLMENT_ID = 'The fulfillmentId provided is invalid',
}

export enum CART_EVENT_ENUM {
  OOS = 'OutOfStock',
  ITEMS_NOT_ADDED = 'ItemsNotAdded',
  ITEMS_REQUESTED_NOT_ADDED = 'ItemsRequestedNotAdded',
  ITEM_NOT_ENGRAVED = 'ItemEngravingError',
  ADDRESS_CHANGE = 'AddressChange',
  LOCATION_AVAILABILITY = 'LocationAvailability',
  PARTNER_PRODUCT_CONFIGS = 'PartnerProductConfigs',
  REMOVED_EXISTING_ITEMS = 'RemovedExistingCartItems',
  RETAILER_MIN = 'RetailerMinNotMet',
  NO_ITEMS_IN_CART = 'NoItemsInCart',
  INVALID_ID = 'InvalidId',
  NO_ID = 'NoId',
  CART_CHECKOUT_PROCESSED = 'CartCheckoutProcessed',
  NEW_CART = 'NewCart',
  DEFAULT = 'CartError',
  ITEM_QTY_CHANGE = 'ItemQuantityChange',
  ITEM_ID_NOT_FOUND = 'ItemIdNotFound',
  ITEMS_REMOVED = 'ItemsRemoved',
}

export enum ENUM_ADDRESS_TYPE {
  SHIPPING = 'shipping',
  BILLING = 'billing',
}
