import type { IApiResponseWithData, IAuth } from '../types';
import type { HttpClient, IHttpClientOptions, IRequestOptions } from './utils';
import { getFetchImplementation } from './utils';

interface IPaymentAuthConfig {
  apiKey: string;

  baseURL: string;
}

/**
 * Represents an payment authenticated service for making HTTP requests.
 */
export class PaymentAuthenticatedService {
  private static instance: PaymentAuthenticatedService | null = null;

  private readonly apiKey: string;

  private readonly baseURL: string;

  private accessToken: string | null = null;

  private tokenExpiration: number | null = null;

  private isAuthenticating = false;

  private readonly httpClient: HttpClient;

  private constructor(config: IPaymentAuthConfig) {
    this.apiKey = config.apiKey;
    this.baseURL = config.baseURL;
    this.httpClient = getFetchImplementation();
  }

  /**
   * Returns an instance of PaymentAuthenticatedClient. This method follows the singleton pattern,
   * meaning that it ensures only one instance of PaymentAuthenticatedClient is created.
   *
   * @param {IPaymentAuthConfig} config - The configuration object used to initialize the PaymentAuthenticatedClient instance.
   * @return {PaymentAuthenticatedService} An instance of PaymentAuthenticatedClient.
   */
  public static getInstance(config: IPaymentAuthConfig): PaymentAuthenticatedService {
    if (!PaymentAuthenticatedService.instance) {
      PaymentAuthenticatedService.instance = new PaymentAuthenticatedService(config);
    }

    return PaymentAuthenticatedService.instance;
  }

  /**
   * Retrieves a unique key based on the userID, password, and baseURL.
   *
   * @return {string} The unique key generated by concatenating the userID, password, and baseURL.
   */
  public getUniqueKey(): string {
    return `${this.apiKey}_${this.baseURL}`;
  }

  /**
   * Authenticates the user with the LiquidCommerce Payment API.
   *
   * This method sends a POST request to the /api/payment-authentication endpoint,
   * and stores the received access token and token expiration time.
   *
   * @returns A Promise that resolves to void.
   * @throws An Error if the authentication fails.
   * @async
   */
  public async authenticate(): Promise<void> {
    if (this.isAuthenticating) {
      // If already authenticating, wait for it to complete
      await new Promise((resolve) => {
        const checkAuth = () => {
          if (!this.isAuthenticating) {
            resolve(undefined);
          } else {
            setTimeout(checkAuth, 100);
          }
        };

        checkAuth();
      });
      return;
    }

    this.isAuthenticating = true;
    try {
      const response = await this.requestWithoutAuth<IApiResponseWithData<IAuth>>(
        '/payment-authentication',
        { method: 'GET' }
      );
      this.accessToken = response?.data?.token;
      this.tokenExpiration = Date.now() + response?.data?.exp * 1000;
    } catch (error) {
      console.error('Payment Authentication failed:', error);
      throw new Error('Failed to authenticate with LiquidCommerce Payment API');
    } finally {
      this.isAuthenticating = false;
    }
  }

  private async requestWithoutAuth<T>(path: string, options: IRequestOptions): Promise<T> {
    const url = new URL(`api${path}`, this.baseURL);
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      'X-LIQUID-API-KEY': this.apiKey,
      ...options.headers,
    };

    const fetchOptions: IHttpClientOptions = {
      method: options.method,
      headers,
      body: options.body ? JSON.stringify(options.body) : undefined,
    };

    const response = await this.httpClient(url.toString(), fetchOptions);

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    return response.json();
  }

  /**
   * Checks if the token is expired.
   *
   * @returns {boolean} Returns true if the token is expired, otherwise returns false.
   */
  isTokenExpired(): boolean {
    return this.tokenExpiration ? Date.now() >= this.tokenExpiration : true;
  }

  /**
   * Sends an HTTP request to the specified path with the provided options and returns a Promise that resolves to the response data.
   *
   * @param path - The path to send the request to.
   * @param options - The options for the request, including method, headers, and body.
   * @returns A Promise that resolves to the response data.
   * @throws {Error} If the response is not successful (status is not ok).
   */
  private async request<T>(path: string, options: IRequestOptions): Promise<T> {
    try {
      if (!this.accessToken || this.isTokenExpired()) {
        await this.authenticate();
      }

      const url = new URL(`api${path}`, this.baseURL);
      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.accessToken}`,
        ...options.headers,
      };

      const fetchOptions: IHttpClientOptions = {
        method: options.method,
        headers,
        body: options.body ? JSON.stringify(options.body) : undefined,
      };

      const response = await this.httpClient(url.toString(), fetchOptions);

      let responseData;
      try {
        responseData = await response.json();
      } catch (error) {
        // If JSON parsing fails, try to get the text
        const text = await response.text().catch(() => `HTTP error! status: ${response.status}`);
        responseData = { message: text || error };
      }

      if (!response.ok) {
        // For error responses, create a structured error object
        const errorObj = {
          ...responseData,
          status: response.status,
          message: responseData?.message || `HTTP error! status: ${response.status}`,
        };

        throw errorObj;
      }

      return responseData;
    } catch (error) {
      throw error;
    }
  }

  /**
   * Sends a GET request to the specified path with optional headers.
   *
   * @param {string} path - The path to send the request to.
   * @param {Record<string, string>} [headers] - Optional headers to include in the request.
   * @return {Promise<T>} - A promise that resolves to the response data.
   */
  public async get<T = any>(path: string, headers?: Record<string, string>): Promise<T> {
    return this.request<T>(path, { method: 'GET', headers });
  }

  /**
   * Sends a POST request to the specified path with optional body and headers.
   *
   * @param {string} path - The path to send the POST request to.
   * @param {any} [body] - The optional body of the request.
   * @param {Record<string, string>} [headers] - The optional headers of the request.
   *
   * @return {Promise<T>} - A Promise that resolves to the response of the request.
   *
   * @throws {Error} - If an error occurs while making the request.
   */
  public async post<T = any>(
    path: string,
    body?: any,
    headers?: Record<string, string>
  ): Promise<T> {
    return this.request<T>(path, { method: 'POST', body, headers });
  }

  /**
   * Sends a PUT request to the specified path with optional request body and headers.
   *
   * @param {string} path - The path where the PUT request will be sent.
   * @param {any} [body] - The optional body of the request.
   * @param {Record<string, string>} [headers] - The optional headers of the request.
   * @return {Promise<T>} A Promise that resolves with the response data.
   */
  public async put<T = any>(
    path: string,
    body?: any,
    headers?: Record<string, string>
  ): Promise<T> {
    return this.request<T>(path, { method: 'PUT', body, headers });
  }

  /**
   * Deletes a resource from the server using the HTTP DELETE method.
   *
   * @param path - The path of the resource to delete.
   * @param headers - Optional headers to include in the request.
   * @returns A promise that resolves to the deleted resource.
   */
  public async delete<T = any>(path: string, headers?: Record<string, string>): Promise<T> {
    return this.request<T>(path, { method: 'DELETE', headers });
  }
}
