name: Lint and Build check

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: |
          npm install -g pnpm@9.5.0
          pnpm install

      - name: Lint and test
        run: |
          pnpm format
          pnpm lint
          pnpm test

      - name: Build SDK
        run: pnpm build