name: Deploy SDK

on:
  push:
    branches:
      - beta
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          clean: true

      - name: Pull latest changes
        run: git pull origin ${{ github.ref }}

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: |
          npm install -g pnpm@9.5.0
          pnpm install

      - name: Set up Git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Lint and test
        run: |
          pnpm lint

      - name: Build SDK
        run: pnpm build

      - name: Update package.json for NPM organization
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            sed -i 's/"name": ".*"/"name": "@liquidcommerce\/cloud-sdk"/' package.json
          else
            sed -i 's/"name": ".*"/"name": "@liquidcommercedev\/cloud-sdk"/' package.json
          fi
          cat package.json  # Optional: for debugging, to see the updated package.json

      - name: Set up NPM Token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.CLOUD_SDK_NPM_TOKEN }}" > ~/.npmrc
          cat ~/.npmrc  # Optional: to debug and confirm the token is set correctly

      - name: Generate changelog
        env:
          NPM_TOKEN: ${{ secrets.CLOUD_SDK_NPM_TOKEN }}
        run: |
          pnpm changelog
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"

      - name: Configure Git
        env:
          GIT_CREDENTIALS: ${{ secrets.CLOUD_GIT_CREDENTIALS }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://${GIT_CREDENTIALS}@github.com/".insteadOf "https://github.com/"

      - name: Semantic Release
        env:
          GIT_CREDENTIALS: ${{ secrets.CLOUD_GIT_CREDENTIALS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.CLOUD_SDK_NPM_TOKEN }}
        run: pnpm semantic-release

      - name: Upload UMD to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "${GCP_SA_KEY}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gsutil cp umd/liquidcommerce-cloud-sdk.min.js \
          $(if [ "${GITHUB_REF}" == "refs/heads/main" ]; then echo "gs://liquid-commerse-assets/sdk/cloud/liquidcommerce-cloud-sdk.min.js"; else echo "gs://liquid-commerse-assets/sdk/cloud/stage/liquidcommerce-cloud-sdk.min.js"; fi)