on:
  push:
    branches:
      - master
      - beta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci
          git checkout package.json

      - name: Create env file
        if: github.ref == 'refs/heads/beta'
        run: |
          echo DEV_API_URL=${{ secrets.DEV_API_URL }} > .env

      - name: Build
        run: npm run build

      - name: Set Variables
        shell: bash
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          secret_name='liquid-npmrc-staging'; if [ "$branch" = 'master' ]; then secret_name='liquid-npmrc'; fi;
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "secret_name=$secret_name" >> $GITHUB_OUTPUT
        id: variables

      - name: Check Variables
        shell: bash
        run: |
          echo "branch=${{ steps.variables.outputs.branch }}"
          echo "secret_name=${{ steps.variables.outputs.secret_name }}"

      - name: Auth Gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set npm and git credentials
        run: |
          gcloud secrets versions access latest --secret=${{ steps.variables.outputs.secret_name }} --out-file=.npmrc
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Prerelease npm
        if: github.ref == 'refs/heads/beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Release npm
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release
          ## Sed for linux only. On macOS use sed -i '' -e 's/@liquidcommercedev/@liquidcommerce/g' {} +
          find . -name "package.json" -exec sed -i 's/@liquidcommercedev/@liquidcommerce/g' {} +
          npm run build
          npm publish --access public

      - name: Release to google cloud storage staging
        run: |
          version=$(cat package.json | jq -r '.version')
          gsutil cp cdn/sdk.js gs://liquid-sdk/liquid-client/versions/$version/sdk.js
          gsutil cp cdn/sdk.js gs://liquid-sdk/staging/sdk.js

      - name: Release to google cloud storage
        if: github.ref == 'refs/heads/master'
        run: |
          gsutil cp cdn/sdk.js gs://liquid-sdk/sdk.js
